name: exoplanet
description: A Flutter app to explore exoplanets from NASA API.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  cached_network_image: ^3.3.1
  retry: ^3.1.2
  cupertino_icons: ^1.0.8
  http: ^1.3.0 # <--- ini penting untuk akses API

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # Tambahkan asset jika kamu ingin pakai gambar nanti
  assets:
    - assets/exoplanets.json

# flutter:
#   assets:
#     - assets/exoplanets.json